name: Trigger SAP iFlow

on:
  push:
    branches:
      - main  # Triggered by pushing to main

jobs:
  trigger-iflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get OAuth token
        id: get_token
        run: |
          response=$(curl --silent --show-error --write-out "HTTPSTATUS:%{http_code}" --request POST \
            --url "${{ secrets.TOKEN_URL }}" \
            --header "Content-Type: application/x-www-form-urlencoded" \
            --data "grant_type=client_credentials&client_id=${{ secrets.CLIENT_ID }}&client_secret=${{ secrets.CLIENT_SECRET }}")

          body=$(echo "$response" | sed -e 's/HTTPSTATUS\:.*//g')
          status=$(echo "$response" | tr -d '\n' | sed -e 's/.*HTTPSTATUS://')

          echo "Status code: $status"
          echo "Response body: $body"

          access_token=$(echo "$body" | jq -r '.access_token')
          echo "access_token=$access_token"
          echo "token=$access_token" >> $GITHUB_OUTPUT

      - name: Trigger iFlow
        run: |
          curl --request POST \
            --url "https://68913245trial.it-cpitrial05-rt.cfapps.us10-001.hana.ondemand.com/http/dummyiflow" \
            --header "Authorization: Bearer ${{ steps.get_token.outputs.token }}" \
            --header "Content-Type: application/json" \
            --data '{"sample":"payload"}'



